### PR TITLE
Updating to babel 6

### PR DESCRIPTION
**Pull request by FuzzOli87**
Updating this so it can use babel 6

### CODE REVIEW

**Comment by quozd** [comment]
Anyone here? Pls merge this stuff

**Comment by CrabDude** [comment]
@quozd I was hoping to have some people verify in the other threads since I didn't have a chance to review it myself yet. Will verify in a bit.

**Comment by jeremyckahn** [comment]
I can confirm that this fixes #7 for me.

**Comment by CrabDude** [comment]
I tried running this, and while it eliminates the options error, I can't get it yet to debug my file... Trying to get it to work. Will follow-up.

**Comment by Sigfried** [comment]
Fixes #7 for me as well.

**Pull request merged**
